spring.application.name=igendabus-smart

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/igendabus_smart_db
spring.datasource.username=postgres
spring.datasource.password=Rugwiza2020
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080